server:
  port: 9100

security:
  jwt:
    public-key: classpath:public.txt

logging:
  level:
    org:
      hibernate:
       SQL: DEBUG

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
      url: jdbc:mysql://localhost:3306/iskool
      username: admin
      password: admin
      initialization-mode: always
  jpa:
      database: mysql
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect