package com.sportsit.iskool.dao.model;
// Generated Aug 24, 2019 6:56:06 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="department"
    ,catalog="iskool"
)
public class Department  implements java.io.Serializable {


     private int id;
     private Organization organization;
     private String name;
     private String description;
     private Set departmentEmployeeMappings = new HashSet(0);

    public Department() {
    }

	
    public Department(int id, Organization organization, String name) {
        this.id = id;
        this.organization = organization;
        this.name = name;
    }
    public Department(int id, Organization organization, String name, String description, Set departmentEmployeeMappings) {
       this.id = id;
       this.organization = organization;
       this.name = name;
       this.description = description;
       this.departmentEmployeeMappings = departmentEmployeeMappings;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="organization_id", nullable=false)
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="department")
    public Set getDepartmentEmployeeMappings() {
        return this.departmentEmployeeMappings;
    }
    
    public void setDepartmentEmployeeMappings(Set departmentEmployeeMappings) {
        this.departmentEmployeeMappings = departmentEmployeeMappings;
    }




}


