package com.sportsit.iskool.dao.model;
// Generated Aug 24, 2019 6:56:06 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmployeeSubjectMapping generated by hbm2java
 */
@Entity
@Table(name="employee_subject_mapping"
    ,catalog="iskool"
)
public class EmployeeSubjectMapping  implements java.io.Serializable {


     private int id;
     private Academicyear academicyear;
     private Subject subject;
     private Employee employee;
     private Set studentSubjectEmployeeMappings = new HashSet(0);

    public EmployeeSubjectMapping() {
    }

	
    public EmployeeSubjectMapping(int id, Academicyear academicyear, Subject subject, Employee employee) {
        this.id = id;
        this.academicyear = academicyear;
        this.subject = subject;
        this.employee = employee;
    }
    public EmployeeSubjectMapping(int id, Academicyear academicyear, Subject subject, Employee employee, Set studentSubjectEmployeeMappings) {
       this.id = id;
       this.academicyear = academicyear;
       this.subject = subject;
       this.employee = employee;
       this.studentSubjectEmployeeMappings = studentSubjectEmployeeMappings;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="academicyear_id", nullable=false)
    public Academicyear getAcademicyear() {
        return this.academicyear;
    }
    
    public void setAcademicyear(Academicyear academicyear) {
        this.academicyear = academicyear;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="subject_id", nullable=false)
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="employeeSubjectMapping")
    public Set getStudentSubjectEmployeeMappings() {
        return this.studentSubjectEmployeeMappings;
    }
    
    public void setStudentSubjectEmployeeMappings(Set studentSubjectEmployeeMappings) {
        this.studentSubjectEmployeeMappings = studentSubjectEmployeeMappings;
    }




}


