package com.sportsit.iskool.dao.model;
// Generated Aug 24, 2019 6:56:06 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OauthRefreshToken generated by hbm2java
 */
@Entity
@Table(name="oauth_refresh_token"
    ,catalog="iskool"
)
public class OauthRefreshToken  implements java.io.Serializable {


     private String tokenId;
     private byte[] token;
     private byte[] authentication;

    public OauthRefreshToken() {
    }

	
    public OauthRefreshToken(String tokenId) {
        this.tokenId = tokenId;
    }
    public OauthRefreshToken(String tokenId, byte[] token, byte[] authentication) {
       this.tokenId = tokenId;
       this.token = token;
       this.authentication = authentication;
    }
   
     @Id 
    
    @Column(name="token_id", unique=true, nullable=false, length=256)
    public String getTokenId() {
        return this.tokenId;
    }
    
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }
    
    @Column(name="token")
    public byte[] getToken() {
        return this.token;
    }
    
    public void setToken(byte[] token) {
        this.token = token;
    }
    
    @Column(name="authentication")
    public byte[] getAuthentication() {
        return this.authentication;
    }
    
    public void setAuthentication(byte[] authentication) {
        this.authentication = authentication;
    }




}


