package com.sportsit.iskool.dao.model;
// Generated Aug 24, 2019 6:56:06 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OauthCode generated by hbm2java
 */
@Entity
@Table(name="oauth_code"
    ,catalog="iskool"
)
public class OauthCode  implements java.io.Serializable {


     private String code;
     private byte[] authentication;

    public OauthCode() {
    }

	
    public OauthCode(String code) {
        this.code = code;
    }
    public OauthCode(String code, byte[] authentication) {
       this.code = code;
       this.authentication = authentication;
    }
   
     @Id 
    
    @Column(name="code", unique=true, nullable=false, length=256)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="authentication")
    public byte[] getAuthentication() {
        return this.authentication;
    }
    
    public void setAuthentication(byte[] authentication) {
        this.authentication = authentication;
    }




}


