package com.sportsit.iskool.dao.model;
// Generated Aug 24, 2019 6:56:06 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OauthClientDetails generated by hbm2java
 */
@Entity
@Table(name="oauth_client_details"
    ,catalog="iskool"
    , uniqueConstraints = {@UniqueConstraint(columnNames="client_secret"), @UniqueConstraint(columnNames="client_id")} 
)
public class OauthClientDetails  implements java.io.Serializable {


     private int id;
     private Organization organization;
     private String clientId;
     private String clientSecret;
     private String webServerRedirectUri;
     private String authorities;
     private Integer accessTokenValidity;
     private Integer refreshTokenValidity;
     private String additionalInformation;
     private String autoapprove;
     private String authorizedGrantTypes;
     private Set orgResourceScopes = new HashSet(0);

    public OauthClientDetails() {
    }

	
    public OauthClientDetails(int id, Organization organization, String clientId, String clientSecret) {
        this.id = id;
        this.organization = organization;
        this.clientId = clientId;
        this.clientSecret = clientSecret;
    }
    public OauthClientDetails(int id, Organization organization, String clientId, String clientSecret, String webServerRedirectUri, String authorities, Integer accessTokenValidity, Integer refreshTokenValidity, String additionalInformation, String autoapprove, String authorizedGrantTypes, Set orgResourceScopes) {
       this.id = id;
       this.organization = organization;
       this.clientId = clientId;
       this.clientSecret = clientSecret;
       this.webServerRedirectUri = webServerRedirectUri;
       this.authorities = authorities;
       this.accessTokenValidity = accessTokenValidity;
       this.refreshTokenValidity = refreshTokenValidity;
       this.additionalInformation = additionalInformation;
       this.autoapprove = autoapprove;
       this.authorizedGrantTypes = authorizedGrantTypes;
       this.orgResourceScopes = orgResourceScopes;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="organization_id", nullable=false)
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
    
    @Column(name="client_id", unique=true, nullable=false, length=256)
    public String getClientId() {
        return this.clientId;
    }
    
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }
    
    @Column(name="client_secret", unique=true, nullable=false, length=256)
    public String getClientSecret() {
        return this.clientSecret;
    }
    
    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
    }
    
    @Column(name="web_server_redirect_uri", length=256)
    public String getWebServerRedirectUri() {
        return this.webServerRedirectUri;
    }
    
    public void setWebServerRedirectUri(String webServerRedirectUri) {
        this.webServerRedirectUri = webServerRedirectUri;
    }
    
    @Column(name="authorities", length=256)
    public String getAuthorities() {
        return this.authorities;
    }
    
    public void setAuthorities(String authorities) {
        this.authorities = authorities;
    }
    
    @Column(name="access_token_validity")
    public Integer getAccessTokenValidity() {
        return this.accessTokenValidity;
    }
    
    public void setAccessTokenValidity(Integer accessTokenValidity) {
        this.accessTokenValidity = accessTokenValidity;
    }
    
    @Column(name="refresh_token_validity")
    public Integer getRefreshTokenValidity() {
        return this.refreshTokenValidity;
    }
    
    public void setRefreshTokenValidity(Integer refreshTokenValidity) {
        this.refreshTokenValidity = refreshTokenValidity;
    }
    
    @Column(name="additional_information", length=500)
    public String getAdditionalInformation() {
        return this.additionalInformation;
    }
    
    public void setAdditionalInformation(String additionalInformation) {
        this.additionalInformation = additionalInformation;
    }
    
    @Column(name="autoapprove", length=256)
    public String getAutoapprove() {
        return this.autoapprove;
    }
    
    public void setAutoapprove(String autoapprove) {
        this.autoapprove = autoapprove;
    }
    
    @Column(name="authorized_grant_types", length=256)
    public String getAuthorizedGrantTypes() {
        return this.authorizedGrantTypes;
    }
    
    public void setAuthorizedGrantTypes(String authorizedGrantTypes) {
        this.authorizedGrantTypes = authorizedGrantTypes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="oauthClientDetails")
    public Set getOrgResourceScopes() {
        return this.orgResourceScopes;
    }
    
    public void setOrgResourceScopes(Set orgResourceScopes) {
        this.orgResourceScopes = orgResourceScopes;
    }




}


