package com.sportsit.iskool.dao.model;
// Generated Aug 24, 2019 6:56:06 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OauthClientToken generated by hbm2java
 */
@Entity
@Table(name="oauth_client_token"
    ,catalog="iskool"
)
public class OauthClientToken  implements java.io.Serializable {


     private String authenticationId;
     private String tokenId;
     private String oauthClientTokencol;
     private byte[] token;
     private String user;

    public OauthClientToken() {
    }

	
    public OauthClientToken(String authenticationId) {
        this.authenticationId = authenticationId;
    }
    public OauthClientToken(String authenticationId, String tokenId, String oauthClientTokencol, byte[] token, String user) {
       this.authenticationId = authenticationId;
       this.tokenId = tokenId;
       this.oauthClientTokencol = oauthClientTokencol;
       this.token = token;
       this.user = user;
    }
   
     @Id 
    
    @Column(name="authentication_id", unique=true, nullable=false, length=256)
    public String getAuthenticationId() {
        return this.authenticationId;
    }
    
    public void setAuthenticationId(String authenticationId) {
        this.authenticationId = authenticationId;
    }
    
    @Column(name="token_id", length=256)
    public String getTokenId() {
        return this.tokenId;
    }
    
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }
    
    @Column(name="oauth_client_tokencol", length=45)
    public String getOauthClientTokencol() {
        return this.oauthClientTokencol;
    }
    
    public void setOauthClientTokencol(String oauthClientTokencol) {
        this.oauthClientTokencol = oauthClientTokencol;
    }
    
    @Column(name="token")
    public byte[] getToken() {
        return this.token;
    }
    
    public void setToken(byte[] token) {
        this.token = token;
    }
    
    @Column(name="user", length=45)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }




}


