package com.sportsit.iskool.dao.model;
// Generated Aug 24, 2019 6:56:06 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Organization generated by hbm2java
 */
@Entity
@Table(name="organization"
    ,catalog="iskool"
)
public class Organization  implements java.io.Serializable {


     private int id;
     private String name;
     private String address;
     private Set employees = new HashSet(0);
     private Set academicyears = new HashSet(0);
     private Set students = new HashSet(0);
     private Set departments = new HashSet(0);
     private Set oauthClientDetailses = new HashSet(0);

    public Organization() {
    }

	
    public Organization(int id, String name, String address) {
        this.id = id;
        this.name = name;
        this.address = address;
    }
    public Organization(int id, String name, String address, Set employees, Set academicyears, Set students, Set departments, Set oauthClientDetailses) {
       this.id = id;
       this.name = name;
       this.address = address;
       this.employees = employees;
       this.academicyears = academicyears;
       this.students = students;
       this.departments = departments;
       this.oauthClientDetailses = oauthClientDetailses;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false, length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="address", nullable=false, length=500)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organization")
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organization")
    public Set getAcademicyears() {
        return this.academicyears;
    }
    
    public void setAcademicyears(Set academicyears) {
        this.academicyears = academicyears;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organization")
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organization")
    public Set getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set departments) {
        this.departments = departments;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organization")
    public Set getOauthClientDetailses() {
        return this.oauthClientDetailses;
    }
    
    public void setOauthClientDetailses(Set oauthClientDetailses) {
        this.oauthClientDetailses = oauthClientDetailses;
    }




}


