package com.sportsit.iskool.dao.model;
// Generated Aug 24, 2019 6:56:06 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrgResourceScope generated by hbm2java
 */
@Entity
@Table(name="org_resource_scope"
    ,catalog="iskool"
)
public class OrgResourceScope  implements java.io.Serializable {


     private int id;
     private Resource resource;
     private OauthClientDetails oauthClientDetails;
     private String scope;

    public OrgResourceScope() {
    }

	
    public OrgResourceScope(int id, Resource resource, OauthClientDetails oauthClientDetails) {
        this.id = id;
        this.resource = resource;
        this.oauthClientDetails = oauthClientDetails;
    }
    public OrgResourceScope(int id, Resource resource, OauthClientDetails oauthClientDetails, String scope) {
       this.id = id;
       this.resource = resource;
       this.oauthClientDetails = oauthClientDetails;
       this.scope = scope;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="resource_id", nullable=false)
    public Resource getResource() {
        return this.resource;
    }
    
    public void setResource(Resource resource) {
        this.resource = resource;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="oauth_client_details_id", nullable=false)
    public OauthClientDetails getOauthClientDetails() {
        return this.oauthClientDetails;
    }
    
    public void setOauthClientDetails(OauthClientDetails oauthClientDetails) {
        this.oauthClientDetails = oauthClientDetails;
    }
    
    @Column(name="scope", length=45)
    public String getScope() {
        return this.scope;
    }
    
    public void setScope(String scope) {
        this.scope = scope;
    }




}


