package com.sportsit.iskool.dao.model;
// Generated Aug 24, 2019 6:56:06 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parent generated by hbm2java
 */
@Entity
@Table(name="parent"
    ,catalog="iskool"
)
public class Parent  implements java.io.Serializable {


     private int id;
     private String firstname;
     private String lastname;
     private String username;
     private String password;
     private String email;
     private String mobile;
     private int enabled;
     private int expired;
     private Date created;
     private Date lastupdated;
     private Set<ParentRoleMapping> parentRoleMappings = new HashSet<ParentRoleMapping>(0);
     private Set<StudentParentMapping> studentParentMappings = new HashSet<StudentParentMapping>(0);

    public Parent() {
    }

	
    public Parent(int id, String firstname, String lastname, String username, String password, String email, String mobile, int enabled, int expired, Date created, Date lastupdated) {
        this.id = id;
        this.firstname = firstname;
        this.lastname = lastname;
        this.username = username;
        this.password = password;
        this.email = email;
        this.mobile = mobile;
        this.enabled = enabled;
        this.expired = expired;
        this.created = created;
        this.lastupdated = lastupdated;
    }
    public Parent(int id, String firstname, String lastname, String username, String password, String email, String mobile, int enabled, int expired, Date created, Date lastupdated, Set<ParentRoleMapping> parentRoleMappings, Set<StudentParentMapping> studentParentMappings) {
       this.id = id;
       this.firstname = firstname;
       this.lastname = lastname;
       this.username = username;
       this.password = password;
       this.email = email;
       this.mobile = mobile;
       this.enabled = enabled;
       this.expired = expired;
       this.created = created;
       this.lastupdated = lastupdated;
       this.parentRoleMappings = parentRoleMappings;
       this.studentParentMappings = studentParentMappings;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="firstname", nullable=false, length=45)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    
    @Column(name="lastname", nullable=false, length=45)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    
    @Column(name="username", nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="mobile", nullable=false, length=45)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    @Column(name="enabled", nullable=false)
    public int getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(int enabled) {
        this.enabled = enabled;
    }
    
    @Column(name="expired", nullable=false)
    public int getExpired() {
        return this.expired;
    }
    
    public void setExpired(int expired) {
        this.expired = expired;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastupdated", nullable=false, length=19)
    public Date getLastupdated() {
        return this.lastupdated;
    }
    
    public void setLastupdated(Date lastupdated) {
        this.lastupdated = lastupdated;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="parent")
    public Set getParentRoleMappings() {
        return this.parentRoleMappings;
    }
    
    public void setParentRoleMappings(Set<ParentRoleMapping> parentRoleMappings) {
        this.parentRoleMappings = parentRoleMappings;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="parent")
    public Set getStudentParentMappings() {
        return this.studentParentMappings;
    }
    
    public void setStudentParentMappings(Set<StudentParentMapping> studentParentMappings) {
        this.studentParentMappings = studentParentMappings;
    }




}


