package com.sportsit.iskool.dao.model;
// Generated Aug 24, 2019 6:56:06 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
    ,catalog="iskool"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Role  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private Set<EmployeeRoleMapping> employeeRoleMappings = new HashSet<EmployeeRoleMapping>(0);
     private Set<StudentRoleMapping> studentRoleMappings = new HashSet<StudentRoleMapping>(0);
     private Set<ParentRoleMapping> parentRoleMappings = new HashSet<ParentRoleMapping>(0);

    public Role() {
    }

	
    public Role(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Role(int id, String name, String description, Set<EmployeeRoleMapping> employeeRoleMappings, Set<StudentRoleMapping> studentRoleMappings, Set<ParentRoleMapping> parentRoleMappings) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.employeeRoleMappings = employeeRoleMappings;
       this.studentRoleMappings = studentRoleMappings;
       this.parentRoleMappings = parentRoleMappings;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="name", unique=true, nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="description", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="role")
    public Set<EmployeeRoleMapping> getEmployeeRoleMappings() {
        return this.employeeRoleMappings;
    }
    
    public void setEmployeeRoleMappings(Set<EmployeeRoleMapping> employeeRoleMappings) {
        this.employeeRoleMappings = employeeRoleMappings;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="role")
    public Set<StudentRoleMapping> getStudentRoleMappings() {
        return this.studentRoleMappings;
    }
    
    public void setStudentRoleMappings(Set<StudentRoleMapping> studentRoleMappings) {
        this.studentRoleMappings = studentRoleMappings;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="role")
    public Set<ParentRoleMapping> getParentRoleMappings() {
        return this.parentRoleMappings;
    }
    
    public void setParentRoleMappings(Set<ParentRoleMapping> parentRoleMappings) {
        this.parentRoleMappings = parentRoleMappings;
    }




}


