package com.sportsit.iskool.dao.model;
// Generated Aug 24, 2019 6:56:06 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SectionAcademicyearMapping generated by hbm2java
 */
@Entity
@Table(name="section_academicyear_mapping"
    ,catalog="iskool"
)
public class SectionAcademicyearMapping  implements java.io.Serializable {


     private int id;
     private Academicyear academicyear;
     private Section section;

    public SectionAcademicyearMapping() {
    }

    public SectionAcademicyearMapping(int id, Academicyear academicyear, Section section) {
       this.id = id;
       this.academicyear = academicyear;
       this.section = section;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="academicyear_id", nullable=false)
    public Academicyear getAcademicyear() {
        return this.academicyear;
    }
    
    public void setAcademicyear(Academicyear academicyear) {
        this.academicyear = academicyear;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="section_id", nullable=false)
    public Section getSection() {
        return this.section;
    }
    
    public void setSection(Section section) {
        this.section = section;
    }




}


