package com.sportsit.iskool.dao.model;
// Generated Aug 24, 2019 6:56:06 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StudentSubjectEmployeeMapping generated by hbm2java
 */
@Entity
@Table(name="student_subject_employee_mapping"
    ,catalog="iskool"
)
public class StudentSubjectEmployeeMapping  implements java.io.Serializable {


     private int id;
     private EmployeeSubjectMapping employeeSubjectMapping;
     private Student student;

    public StudentSubjectEmployeeMapping() {
    }

    public StudentSubjectEmployeeMapping(int id, EmployeeSubjectMapping employeeSubjectMapping, Student student) {
       this.id = id;
       this.employeeSubjectMapping = employeeSubjectMapping;
       this.student = student;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_subject_mapping_id", nullable=false)
    public EmployeeSubjectMapping getEmployeeSubjectMapping() {
        return this.employeeSubjectMapping;
    }
    
    public void setEmployeeSubjectMapping(EmployeeSubjectMapping employeeSubjectMapping) {
        this.employeeSubjectMapping = employeeSubjectMapping;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }




}


