package com.sportsit.iskool.dao.model;
// Generated Aug 24, 2019 6:56:06 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name="user_type"
    ,catalog="iskool"
)
public class UserType  implements java.io.Serializable {


     private int id;
     private String student;
     private String parent;
     private String employee;
     private String admin;
     private String superadmin;

    public UserType() {
    }

	
    public UserType(int id) {
        this.id = id;
    }
    public UserType(int id, String student, String parent, String employee, String admin, String superadmin) {
       this.id = id;
       this.student = student;
       this.parent = parent;
       this.employee = employee;
       this.admin = admin;
       this.superadmin = superadmin;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="student", length=45)
    public String getStudent() {
        return this.student;
    }
    
    public void setStudent(String student) {
        this.student = student;
    }
    
    @Column(name="parent", length=45)
    public String getParent() {
        return this.parent;
    }
    
    public void setParent(String parent) {
        this.parent = parent;
    }
    
    @Column(name="employee", length=45)
    public String getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(String employee) {
        this.employee = employee;
    }
    
    @Column(name="admin", length=45)
    public String getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(String admin) {
        this.admin = admin;
    }
    
    @Column(name="superadmin", length=45)
    public String getSuperadmin() {
        return this.superadmin;
    }
    
    public void setSuperadmin(String superadmin) {
        this.superadmin = superadmin;
    }




}


